### Register
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "adminuser@rideshare.com",
  "password": "password",
  "firstName": "First",
  "lastName": "Admin",
  "phoneNumber": "+40700000000",
  "birthDate": "1990-01-01"
}

### Login
POST {{host}}/auth/login
Content-Type: application/json
Authorization: Basic adminuser@rideshare.com password

### Find all
GET {{host}}/locations

### Create Location
POST {{host}}/locations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW51c2VyQHJpZGVzaGFyZS5jb20iLCJleHAiOjE3NTUxNzI3MDcsImlhdCI6MTc1NTE2OTEwNywic2NvcGUiOiJkZWxldGU6dmVoaWNsZSBjcmVhdGU6Ym9va2luZyBtYW5hZ2U6cm9sZSByZWFkOnJpZGUgdXBkYXRlOnZlaGljbGUgdXBkYXRlOmxvY2F0aW9uIHJlYWQ6Ym9va2luZyByZWFkOmxvY2F0aW9uIGNyZWF0ZTp2ZWhpY2xlIG1hbmFnZTp1c2VyIHVwZGF0ZTpyaWRlIGNyZWF0ZTpsb2NhdGlvbiBkZWxldGU6cmlkZSBkZWxldGU6bG9jYXRpb24gY3JlYXRlOnJhdGluZyBjcmVhdGU6cmlkZSBkZWxldGU6Ym9va2luZyByZWFkOnZlaGljbGUgY2FuY2VsOmJvb2tpbmcifQ.cOg2v7OsKWfzceKD7ezQTq8_8jvAJAqTcQ8NuOIEAJViv67eTHNw9wyRu6MYFh2tXDQ5BodsZP1sBdiBQuaIEI8Cljw_cBelVL4Trrfr7AozNdXAFW7JC24FCZ4F3TCgzyAcHG1Rp1blkWK7u4xzqGiqKdT45ujxnN1f98ZNp02a9ZPMGfl_9Gs0iTmjx-Bn_Y-DRbIizeWKkFcEUqosiJrOmrZKK-GxNCgy86P1Hm3-UP-RThax8tjGPxUTynMepQyflt7ao8Nc8iy4RpPH-4zwo7Li4ZiirG0wdc7TgXPvDRlHifbjNTkqt9zYMuxIZXy1bknGy8N0yejmFVU2EQ

{
  "city": "New",
  "county": "New County"
}

